//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowerpower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class medewerkers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public medewerkers()
        {
            this.bestelling = new HashSet<bestelling>();
        }
    
        public int medewerkerid { get; set; }
        public string medewerkernaam { get; set; }
        public string medewerkerachternaam { get; set; }
        public Nullable<int> winkelcode { get; set; }
        public Nullable<bool> medewerkeractief { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bestelling> bestelling { get; set; }
        public virtual winkel winkel { get; set; }
    }
}
