//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Flowerpower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class winkelmand
    {
        public int bestellingid { get; set; }
        public Nullable<int> productid { get; set; }
        public Nullable<int> aantal { get; set; }
        public int bestelregelid { get; set; }
    
        public virtual bestelling bestelling { get; set; }
        public virtual producten producten { get; set; }
    }
}
